name: Build and Deploy Unity WebGL Games

on:
  push:
    branches:
      - main
      - ci-cd
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          [
            "Udemy Day 2 - Carrot Collector",
            "Udemy Day 3 - 3D Dodging",
            "Udemy Day 4 - Balloon Popper",
            "Udemy Day 5 - Block Dodger",
            "Udemy Day 6 - 3D Maze Ball",
            "Udemy Day 7 - Cube Runner",
            "Udemy Day 8 - Monetize Ads",
            "Udemy Day 9 - Coin Collector",
            "Udemy Day 10 - 2D Essentials",
          ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure we get full commit history

      # Restore cached build if no changes
      - name: Restore Cached Build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ${{ matrix.project }}/Library
          key: Library-WebGL-${{ matrix.project }}-${{ hashFiles('**/${{ matrix.project }}/Assets/**', '**/${{ matrix.project }}/ProjectSettings/**') }}
          restore-keys: |
            Library-WebGL-${{ matrix.project }}-

      - name: Setup Unity
        if: steps.cache-build.outputs.cache-hit != 'true' # Only setup Unity if no cache hit
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          unityVersion: 6000.0.29f1
          projectPath: ${{ matrix.project }}

      - name: Build WebGL
        if: steps.cache-build.outputs.cache-hit != 'true' # Only build if cache is invalid
        run: |
          mkdir -p build/${{ matrix.project }}
          unity-editor -batchmode -quit -nographics -buildTarget WebGL -projectPath ${{ matrix.project }} -executeMethod UnityEditor.BuildPipeline.BuildPlayer -logFile build_log.txt
          mv ${{ matrix.project }}/Build/WebGL/* build/${{ matrix.project }}/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          destination_dir: builds
          keep_files: true
